openapi: 3.0.0
info:
  title: tiny-tasks-documentation
  version: 1.0.0
paths:
  /6969/health:
    get:
      summary: get health
      operationId: c_users_haq_documents_bruno_tiny-tasks_get_health_yml
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      servers:
        - url: 'null'
servers: []
components:
  schemas: {}
  requestBodies: {}
  securitySchemes: {}
